/* Autogenerated with kurento-module-creator */

#include <gst/gst.h>
#include "MediaPipeline.hpp"
#include "MediaPipelineImpl.hpp"
#include <KmsMsDataImplFactory.hpp>
#include "KmsMsDataImpl.hpp"
#include <jsonrpc/JsonSerializer.hpp>
#include <KurentoException.hpp>

#define GST_CAT_DEFAULT kurento_kms_ms_data_impl
GST_DEBUG_CATEGORY_STATIC (GST_CAT_DEFAULT);
#define GST_DEFAULT_NAME "KurentoKmsMsDataImpl"

#define FACTORY_NAME "kmsmsdata"

namespace kurento
{
namespace module
{
namespace msdata
{

KmsMsDataImpl::KmsMsDataImpl (const boost::property_tree::ptree &config, std::shared_ptr<MediaPipeline> mediaPipeline)  : MediaElementImpl (config,
                    std::dynamic_pointer_cast<MediaPipelineImpl> (mediaPipeline),
                    FACTORY_NAME) 
{
}

MediaObjectImpl *
KmsMsDataImplFactory::createObject (const boost::property_tree::ptree &config, std::shared_ptr<MediaPipeline> mediaPipeline) const
{
  return new KmsMsDataImpl (config, mediaPipeline);
}

KmsMsDataImpl::StaticConstructor KmsMsDataImpl::staticConstructor;

KmsMsDataImpl::StaticConstructor::StaticConstructor()
{
  GST_DEBUG_CATEGORY_INIT (GST_CAT_DEFAULT, GST_DEFAULT_NAME, 0,
                           GST_DEFAULT_NAME);
}

} /* msdata */
} /* module */
} /* kurento */
