/* Autogenerated with kurento-module-creator */

#include <gst/gst.h>
#include "MediaPipeline.hpp"
#include <KmsSGDImplFactory.hpp>
#include "KmsSGDImpl.hpp"
#include <jsonrpc/JsonSerializer.hpp>
#include <KurentoException.hpp>

#define GST_CAT_DEFAULT kurento_kms_sgd_impl
GST_DEBUG_CATEGORY_STATIC (GST_CAT_DEFAULT);
#define GST_DEFAULT_NAME "KurentoKmsSGDImpl"

namespace kurento
{
namespace module
{
namespace msdatamodule
{

KmsSGDImpl::KmsSGDImpl (const boost::property_tree::ptree &config, std::shared_ptr<MediaPipeline> mediaPipeline)  : FilterImpl (
config, std::dynamic_pointer_cast<MediaObjectImpl> ( mediaPipeline) ) 
{
  g_object_set (element, "filter-factory", "graphsmetadata", NULL);

  g_object_get (G_OBJECT (element), "filter", &graphs, NULL);

  if (graphs == NULL) {
    throw KurentoException (MEDIA_OBJECT_NOT_AVAILABLE,
                            "Media Object SGD not available");
  }

  g_object_unref (graphs);
}

MediaObjectImpl *
KmsSGDImplFactory::createObject (const boost::property_tree::ptree &config, std::shared_ptr<MediaPipeline> mediaPipeline) const
{
  return new KmsSGDImpl (config, mediaPipeline);
}

KmsSGDImpl::StaticConstructor KmsSGDImpl::staticConstructor;

KmsSGDImpl::StaticConstructor::StaticConstructor()
{
  GST_DEBUG_CATEGORY_INIT (GST_CAT_DEFAULT, GST_DEFAULT_NAME, 0,
                           GST_DEFAULT_NAME);
}

} /* msdatamodule */
} /* module */
} /* kurento */
