/* Autogenerated with kurento-module-creator */

#ifndef __KMS_SGD_IMPL_HPP__
#define __KMS_SGD_IMPL_HPP__

#include "FilterImpl.hpp"
#include "KmsSGD.hpp"
#include <EventHandler.hpp>
#include <boost/property_tree/ptree.hpp>

namespace kurento
{
namespace module
{
namespace msdatamodule
{
class KmsSGDImpl;
} /* msdatamodule */
} /* module */
} /* kurento */

namespace kurento
{
void Serialize (std::shared_ptr<kurento::module::msdatamodule::KmsSGDImpl> &object, JsonSerializer &serializer);
} /* kurento */

namespace kurento
{
class MediaPipelineImpl;
} /* kurento */

namespace kurento
{
namespace module
{
namespace msdatamodule
{

class KmsSGDImpl : public FilterImpl, public virtual KmsSGD
{

public:

  KmsSGDImpl (const boost::property_tree::ptree &config, std::shared_ptr<MediaPipeline> mediaPipeline);

  virtual ~KmsSGDImpl () {};

  /* Next methods are automatically implemented by code generator */
  virtual bool connect (const std::string &eventType, std::shared_ptr<EventHandler> handler);
  virtual void invoke (std::shared_ptr<MediaObjectImpl> obj,
                       const std::string &methodName, const Json::Value &params,
                       Json::Value &response);

  virtual void Serialize (JsonSerializer &serializer);

private:
  GstElement *graphs = NULL;

  class StaticConstructor
  {
  public:
    StaticConstructor();
  };

  static StaticConstructor staticConstructor;

};

} /* msdatamodule */
} /* module */
} /* kurento */

#endif /*  __KMS_SGD_IMPL_HPP__ */
