/* Autogenerated with kurento-module-creator */

#include "KmsMsData.hpp"
#include <mutex>

namespace kurento
{
namespace module
{
namespace msdata
{

static std::vector<std::string> hierarchyKmsMsData;
std::once_flag initFlagKmsMsData;

static void
initHierarchy ()
{
  hierarchyKmsMsData.push_back("kurento.MediaElement");
  hierarchyKmsMsData.push_back("kurento.MediaObject");
}

const std::vector<std::string> &
KmsMsData::getHierarchy () const
{
  std::call_once (initFlagKmsMsData,initHierarchy);
  return hierarchyKmsMsData;
}

const std::string&
KmsMsData::getType () const {
  static std::string typeName = "KmsMsData";

  return typeName;
}

const std::string&
KmsMsData::getQualifiedType () const {
  static std::string qualifiedTypeName = getModule() + "." + getType();

  return qualifiedTypeName;
}

const std::string&
KmsMsData::getModule () const {
  static std::string moduleName =  "msdata";

  return moduleName;
}

} /* msdata */
} /* module */
} /* kurento */
