/* Autogenerated with kurento-module-creator */

#include <gst/gst.h>
#include "MediaPipeline.hpp"
#include "KmsMsDataImpl.hpp"
#include "KmsMsDataImplFactory.hpp"
#include "KmsMsDataInternal.hpp"
#include <jsonrpc/JsonSerializer.hpp>
#include <KurentoException.hpp>

using kurento::KurentoException;

namespace kurento
{
namespace module
{
namespace msdata
{

MediaObjectImpl *KmsMsDataImplFactory::createObjectPointer (const boost::property_tree::ptree &conf, const Json::Value &params) const
{
  kurento::JsonSerializer s (false);
  KmsMsDataConstructor constructor;

  s.JsonValue = params;
  constructor.Serialize (s);

  return createObject (conf, constructor.getMediaPipeline() );
}

void
KmsMsDataImpl::invoke (std::shared_ptr<MediaObjectImpl> obj, const std::string &methodName, const Json::Value &params, Json::Value &response)
{
  MediaElementImpl::invoke (obj, methodName, params, response);
}

bool
KmsMsDataImpl::connect (const std::string &eventType, std::shared_ptr<EventHandler> handler)
{

  return MediaElementImpl::connect (eventType, handler);
}

void
KmsMsDataImpl::Serialize (JsonSerializer &serializer)
{
  if (serializer.IsWriter) {
    try {
      Json::Value v (getId() );

      serializer.JsonValue = v;
    } catch (std::bad_cast &e) {
    }
  } else {
    throw KurentoException (MARSHALL_ERROR,
                            "'KmsMsDataImpl' cannot be deserialized as an object");
  }
}
} /* msdata */
} /* module */
} /* kurento */

namespace kurento
{

void
Serialize (std::shared_ptr<kurento::module::msdata::KmsMsDataImpl> &object, JsonSerializer &serializer)
{
  if (serializer.IsWriter) {
    if (object) {
      object->Serialize (serializer);
    }
  } else {
    std::shared_ptr<kurento::MediaObjectImpl> aux;
    aux = kurento::module::msdata::KmsMsDataImplFactory::getObject (JsonFixes::getString(serializer.JsonValue) );
    object = std::dynamic_pointer_cast<kurento::module::msdata::KmsMsDataImpl> (aux);
  }
}

void
Serialize (std::shared_ptr<kurento::module::msdata::KmsMsData> &object, JsonSerializer &serializer)
{
  std::shared_ptr<kurento::module::msdata::KmsMsDataImpl> aux = std::dynamic_pointer_cast<kurento::module::msdata::KmsMsDataImpl> (object);

  Serialize (aux, serializer);
  object = std::dynamic_pointer_cast <kurento::module::msdata::KmsMsData> (aux);
}

} /* kurento */