/* Autogenerated with kurento-module-creator */

#include "KmsMsDataImpl.hpp"

#include <jsonrpc/JsonSerializer.hpp>

namespace kurento
{
namespace module
{
namespace msdata
{

void dummyMsdata ()
{
  {
    JsonSerializer s (true);
    std::shared_ptr<KmsMsData> object;

    s.SerializeNVP (object);
  }
}

} /* msdata */
} /* module */
} /* kurento */
